[2022-12-11T15:38:50.486+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: mongo_etl.zips_mongo manual__2022-12-11T15:33:58.396996+00:00 [queued]>
[2022-12-11T15:38:50.674+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: mongo_etl.zips_mongo manual__2022-12-11T15:33:58.396996+00:00 [queued]>
[2022-12-11T15:38:50.687+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T15:38:50.688+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-11T15:38:50.689+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T15:38:50.923+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): zips_mongo> on 2022-12-11 15:33:58.396996+00:00
[2022-12-11T15:38:50.982+0000] {standard_task_runner.py:55} INFO - Started process 3111 to run task
[2022-12-11T15:38:51.044+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mongo_etl', 'zips_mongo', 'manual__2022-12-11T15:33:58.396996+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/mongo_etl/mongo_dags.py', '--cfg-path', '/tmp/tmps518w2ad']
[2022-12-11T15:38:51.073+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask zips_mongo
[2022-12-11T15:38:51.786+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 42 for task zips_mongo ((psycopg2.OperationalError) connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "airflow"

(Background on this error at: https://sqlalche.me/e/14/e3q8); 3111)
[2022-12-11T15:38:51.868+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-11T15:38:52.170+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
